// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.8
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

#include <memory>
#include <new>
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_union/union_ci.cpp:35

// *************************************************************
// Inline operations for union MyAnyUnion
// *************************************************************
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_union/discriminant_ci.cpp:195

ACE_INLINE
void
MyAnyUnion::_default ()
{
  this->_reset ();
  this->disc_ = static_cast <AnyUnionEnum> (-1);
}



ACE_INLINE
unsigned long
MyAnyUnion::_tao_member_index (AnyUnionEnum value)
{
  switch (value)
  {
    case ::ANYUNIONENUM2:
    return 0UL;
    default:
    return 1UL;
  }
}

// Accessor to set the discriminant.
ACE_INLINE
void
MyAnyUnion::_d (AnyUnionEnum discval)
{
  if (this->disc_ != discval)
    {
      if (_tao_member_index (this->disc_) != _tao_member_index (discval))
        {
          throw ::CORBA::BAD_PARAM ();
        }
      }
  this->disc_ = discval;
}

// Accessor to get the discriminant.
ACE_INLINE
AnyUnionEnum
MyAnyUnion::_d () const
{
  return this->disc_;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:606

// Accessor to set the member.
ACE_INLINE
void
MyAnyUnion::my_any (const ::CORBA::Any & val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = ::ANYUNIONENUM2;
  ACE_NEW (
      this->u_.my_any_,
      ::CORBA::Any (val)
    );
}

/// Retrieve the member.
ACE_INLINE
const ::CORBA::Any &
MyAnyUnion::my_any () const
{
  if (_tao_member_index (this->disc_) != 0UL)
    {
      throw ::CORBA::BAD_PARAM ();
    }
  return *this->u_.my_any_;
}

/// Retrieve the member.
ACE_INLINE
::CORBA::Any &
MyAnyUnion::my_any ()
{
  if (_tao_member_index (this->disc_) != 0UL)
    {
      throw ::CORBA::BAD_PARAM ();
    }
  return *this->u_.my_any_;
}

