// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
mod2::full::full (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (objref, _tao_collocated, servant, oc)
{
}

ACE_INLINE
mod2::full::full (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ci.cpp:43

ACE_INLINE
mod2::AMH_fullExceptionHolder::AMH_fullExceptionHolder ()
  : exception (nullptr)
{}

ACE_INLINE const char*
mod2::AMH_fullExceptionHolder::_tao_obv_static_repository_id ()
{
  return "IDL:mod2/AMH_fullExceptionHolder:1.0";
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
mod2::AMI_fullHandler::AMI_fullHandler (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (objref, _tao_collocated, servant, oc)
{
}

ACE_INLINE
mod2::AMI_fullHandler::AMI_fullHandler (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
fwd_mixed_intf::concrete_parent::concrete_parent (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (objref, _tao_collocated, servant, oc)
{
}

ACE_INLINE
fwd_mixed_intf::concrete_parent::concrete_parent (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ci.cpp:43

ACE_INLINE
fwd_mixed_intf::AMH_concrete_parentExceptionHolder::AMH_concrete_parentExceptionHolder ()
  : exception (nullptr)
{}

ACE_INLINE const char*
fwd_mixed_intf::AMH_concrete_parentExceptionHolder::_tao_obv_static_repository_id ()
{
  return "IDL:fwd_mixed_intf/AMH_concrete_parentExceptionHolder:1.0";
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
fwd_mixed_intf::AMI_concrete_parentHandler::AMI_concrete_parentHandler (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (objref, _tao_collocated, servant, oc)
{
}

ACE_INLINE
fwd_mixed_intf::AMI_concrete_parentHandler::AMI_concrete_parentHandler (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
fwd_mixed_intf::abstract_parent::abstract_parent ()
{}

ACE_INLINE
fwd_mixed_intf::abstract_parent::abstract_parent (const abstract_parent &rhs)
  : ::CORBA::AbstractBase (rhs)
{}

ACE_INLINE
fwd_mixed_intf::abstract_parent::abstract_parent (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *)
  : ::CORBA::AbstractBase (
        objref,
        _tao_collocated,
        servant
      )
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
fwd_mixed_intf::mixed_abs_first::mixed_abs_first (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::AbstractBase (
        objref,
        _tao_collocated,
        servant
      ),
    fwd_mixed_intf::abstract_parent (
        objref,
        _tao_collocated,
        servant
      ),
  ::CORBA::Object (objref, _tao_collocated, servant, oc)
{
}

ACE_INLINE
fwd_mixed_intf::mixed_abs_first::mixed_abs_first (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
fwd_mixed_intf::AMI_mixed_abs_firstHandler::AMI_mixed_abs_firstHandler (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (objref, _tao_collocated, servant, oc)
{
}

ACE_INLINE
fwd_mixed_intf::AMI_mixed_abs_firstHandler::AMI_mixed_abs_firstHandler (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
fwd_mixed_intf::mixed_conc_first::mixed_conc_first (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (
        objref,
        _tao_collocated,
        servant, oc
      ),
    ::CORBA::AbstractBase (
        objref,
        _tao_collocated,
        servant
      ),
    fwd_mixed_intf::abstract_parent (
        objref,
        _tao_collocated,
        servant
      )
{
}

ACE_INLINE
fwd_mixed_intf::mixed_conc_first::mixed_conc_first (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
fwd_mixed_intf::AMI_mixed_conc_firstHandler::AMI_mixed_conc_firstHandler (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (objref, _tao_collocated, servant, oc)
{
}

ACE_INLINE
fwd_mixed_intf::AMI_mixed_conc_firstHandler::AMI_mixed_conc_firstHandler (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ci.cpp:43

ACE_INLINE
obv_fwd::EnclosingType::EnclosingType ()
{}

ACE_INLINE const char*
obv_fwd::EnclosingType::_tao_obv_static_repository_id ()
{
  return "IDL:obv_fwd/EnclosingType:1.0";
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ci.cpp:43

ACE_INLINE
obv_fwd::ForwardedType::ForwardedType ()
{}

ACE_INLINE const char*
obv_fwd::ForwardedType::_tao_obv_static_repository_id ()
{
  return "IDL:obv_fwd/ForwardedType:1.0";
}

