// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "TestC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/Struct_TypeCode_Static.h"
#include "tao/AnyTypeCode/TypeCode_Struct_Field.h"
#include "tao/AnyTypeCode/Value_TypeCode_Static.h"
#include "tao/AnyTypeCode/TypeCode_Value_Field.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/SystemException.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/AnyTypeCode/Any_Dual_Impl_T.h"
#include "cstring"
#include "memory"

#if !defined (__ACE_INLINE__)
#include "TestC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_exception/exception_cs.cpp:97

Test::InvalidTimestamp::InvalidTimestamp ()
  : ::CORBA::UserException (
        "IDL:Test/InvalidTimestamp:1.0",
        "InvalidTimestamp")
{
}

Test::InvalidTimestamp::InvalidTimestamp (const ::Test::InvalidTimestamp &_tao_excp)
  : ::CORBA::UserException (
        _tao_excp._rep_id (),
        _tao_excp._name ())
{
}

Test::InvalidTimestamp&
Test::InvalidTimestamp::operator= (const ::Test::InvalidTimestamp &_tao_excp)
{
  this->::CORBA::UserException::operator= (_tao_excp);
  return *this;
}

void Test::InvalidTimestamp::_tao_any_destructor (void *_tao_void_pointer)
{
  InvalidTimestamp *_tao_tmp_pointer =
    static_cast<InvalidTimestamp *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

Test::InvalidTimestamp *
Test::InvalidTimestamp::_downcast (::CORBA::Exception *_tao_excp)
{
  return dynamic_cast<InvalidTimestamp *> (_tao_excp);
}

const Test::InvalidTimestamp *
Test::InvalidTimestamp::_downcast (::CORBA::Exception const *_tao_excp)
{
  return dynamic_cast<const InvalidTimestamp *> (_tao_excp);
}

::CORBA::Exception *Test::InvalidTimestamp::_alloc ()
{
  ::CORBA::Exception *retval {};
  ACE_NEW_RETURN (retval, ::Test::InvalidTimestamp, nullptr);
  return retval;
}

::CORBA::Exception *
Test::InvalidTimestamp::_tao_duplicate () const
{
  ::CORBA::Exception *result {};
  ACE_NEW_RETURN (result, ::Test::InvalidTimestamp (*this), nullptr);
  return result;
}

void Test::InvalidTimestamp::_raise () const
{
  throw *this;
}

void Test::InvalidTimestamp::_tao_encode (TAO_OutputCDR &cdr) const
{
  if (!(cdr << *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

void Test::InvalidTimestamp::_tao_decode (TAO_InputCDR &cdr)
{
  if (!(cdr >> *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

// TAO extension - the virtual _type method.
::CORBA::TypeCode_ptr Test::InvalidTimestamp::_tao_type () const
{
  return ::Test::_tc_InvalidTimestamp;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const * const 
    _tao_fields_Test_InvalidTimestamp = nullptr;
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Test_InvalidTimestamp (
  ::CORBA::tk_except,
  "IDL:Test/InvalidTimestamp:1.0",
  "InvalidTimestamp",
  _tao_fields_Test_InvalidTimestamp,
  0);


namespace Test
{
  ::CORBA::TypeCode_ptr const _tc_InvalidTimestamp =
    &_tao_tc_Test_InvalidTimestamp;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_exception/exception_cs.cpp:97

Test::ServerOverload::ServerOverload ()
  : ::CORBA::UserException (
        "IDL:Test/ServerOverload:1.0",
        "ServerOverload")
{
}

Test::ServerOverload::ServerOverload (const ::Test::ServerOverload &_tao_excp)
  : ::CORBA::UserException (
        _tao_excp._rep_id (),
        _tao_excp._name ())
{
}

Test::ServerOverload&
Test::ServerOverload::operator= (const ::Test::ServerOverload &_tao_excp)
{
  this->::CORBA::UserException::operator= (_tao_excp);
  return *this;
}

void Test::ServerOverload::_tao_any_destructor (void *_tao_void_pointer)
{
  ServerOverload *_tao_tmp_pointer =
    static_cast<ServerOverload *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

Test::ServerOverload *
Test::ServerOverload::_downcast (::CORBA::Exception *_tao_excp)
{
  return dynamic_cast<ServerOverload *> (_tao_excp);
}

const Test::ServerOverload *
Test::ServerOverload::_downcast (::CORBA::Exception const *_tao_excp)
{
  return dynamic_cast<const ServerOverload *> (_tao_excp);
}

::CORBA::Exception *Test::ServerOverload::_alloc ()
{
  ::CORBA::Exception *retval {};
  ACE_NEW_RETURN (retval, ::Test::ServerOverload, nullptr);
  return retval;
}

::CORBA::Exception *
Test::ServerOverload::_tao_duplicate () const
{
  ::CORBA::Exception *result {};
  ACE_NEW_RETURN (result, ::Test::ServerOverload (*this), nullptr);
  return result;
}

void Test::ServerOverload::_raise () const
{
  throw *this;
}

void Test::ServerOverload::_tao_encode (TAO_OutputCDR &cdr) const
{
  if (!(cdr << *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

void Test::ServerOverload::_tao_decode (TAO_InputCDR &cdr)
{
  if (!(cdr >> *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

// TAO extension - the virtual _type method.
::CORBA::TypeCode_ptr Test::ServerOverload::_tao_type () const
{
  return ::Test::_tc_ServerOverload;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const * const 
    _tao_fields_Test_ServerOverload = nullptr;
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Test_ServerOverload (
  ::CORBA::tk_except,
  "IDL:Test/ServerOverload:1.0",
  "ServerOverload",
  _tao_fields_Test_ServerOverload,
  0);


namespace Test
{
  ::CORBA::TypeCode_ptr const _tc_ServerOverload =
    &_tao_tc_Test_ServerOverload;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_typecode/alias_typecode.cpp:46

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_Test_Timestamp (
    ::CORBA::tk_alias,
    "IDL:Test/Timestamp:1.0",
    "Timestamp",
    &CORBA::_tc_ulonglong);
  

namespace Test
{
  ::CORBA::TypeCode_ptr const _tc_Timestamp =
    &_tao_tc_Test_Timestamp;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_typecode/value_typecode.cpp:63

static TAO::TypeCode::Value_Field<char const *, ::CORBA::TypeCode_ptr const *> const * const _tao_fields_Test_Red_Herring = 0;
static TAO::TypeCode::Value<char const *,
                     ::CORBA::TypeCode_ptr const *,
                     TAO::TypeCode::Value_Field<char const *, ::CORBA::TypeCode_ptr const *> const *,
                     TAO::Null_RefCount_Policy>
  _tao_tc_Test_Red_Herring (
    ::CORBA::tk_value,
    "IDL:Test/Red_Herring:1.0",
    "Red_Herring",
    ::CORBA::VM_NONE,
    &::CORBA::_tc_null,
    _tao_fields_Test_Red_Herring,
    0);
  

namespace Test
{
  ::CORBA::TypeCode_ptr const _tc_Red_Herring =
    &_tao_tc_Test_Red_Herring;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_cs.cpp:52



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


void
TAO::Value_Traits<Test::Red_Herring>::add_ref (Test::Red_Herring * p)
{
  ::CORBA::add_ref (p);
}

void
TAO::Value_Traits<Test::Red_Herring>::remove_ref (Test::Red_Herring * p)
{
  ::CORBA::remove_ref (p);
}

void
TAO::Value_Traits<Test::Red_Herring>::release (Test::Red_Herring * p)
{
  ::CORBA::remove_ref (p);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Test::Red_Herring *
Test::Red_Herring::_downcast (::CORBA::ValueBase *v)
{
  return dynamic_cast<::Test::Red_Herring *> (v);
}

const char *
Test::Red_Herring::_tao_obv_repository_id () const
{
  return this->_tao_obv_static_repository_id ();
}

void
Test::Red_Herring::_tao_obv_truncatable_repo_ids (Repository_Id_List& ids) const
{
  ids.push_back (this->_tao_obv_static_repository_id ());
}

void
Test::Red_Herring::_tao_any_destructor (void *_tao_void_pointer)
{
  Red_Herring *_tao_tmp_pointer =
    static_cast<Red_Herring *> (_tao_void_pointer);
  ::CORBA::remove_ref (_tao_tmp_pointer);
}

// TAO extension - the virtual _type method.
::CORBA::TypeCode_ptr Test::Red_Herring::_tao_type () const
{
  return ::Test::_tc_Red_Herring;
}

Test::Red_Herring::~Red_Herring ()
{}

::CORBA::Boolean
Test::Red_Herring::_tao_marshal_v (TAO_OutputCDR & strm) const
{
  TAO_ChunkInfo ci (this->is_truncatable_ || this->chunking_);
  return this->_tao_marshal__Test_Red_Herring (strm, ci);
}

::CORBA::Boolean
Test::Red_Herring::_tao_unmarshal_v (TAO_InputCDR & strm)
{
  TAO_ChunkInfo ci (this->is_truncatable_ || this->chunking_, 1);
  return this->_tao_unmarshal__Test_Red_Herring (strm,ci);
}

::CORBA::Boolean
Test::Red_Herring::_tao_match_formal_type (ptrdiff_t formal_type_id) const
{
  return formal_type_id == reinterpret_cast<ptrdiff_t> (Test::Red_Herring::_downcast);
}

::CORBA::Boolean
Test::Red_Herring::_tao_unmarshal (
    TAO_InputCDR &strm,
    Red_Herring *&new_object)
{
  ::CORBA::ValueBase *base {};
  ::CORBA::Boolean is_indirected = false;
  ::CORBA::Boolean is_null_object = false;
  ::CORBA::Boolean const retval =
    ::CORBA::ValueBase::_tao_unmarshal_pre (
        strm,
        base,
        Red_Herring::_tao_obv_static_repository_id (),
        is_null_object,
        is_indirected
      );
  
  ::CORBA::ValueBase_var owner (base);

  if (!retval)
    return false;
  
  if (is_null_object)
    return true;
  
  if (!is_indirected && !base->_tao_unmarshal_v (strm))
    return false;
  
  // Now base must point to the unmarshaled object.
  // Align the pointer to the right subobject.
  new_object = Red_Herring::_downcast (base);
  if (nullptr == new_object)
    return false;
  
  if (is_indirected)
    new_object->_add_ref ();
  
  owner._retn ();
  return true;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Test::Roundtrip.

Test::Roundtrip_ptr
TAO::Objref_Traits<Test::Roundtrip>::duplicate (Test::Roundtrip_ptr p)
{
  return Test::Roundtrip::_duplicate (p);
}

void
TAO::Objref_Traits<Test::Roundtrip>::release (Test::Roundtrip_ptr p)
{
  ::CORBA::release (p);
}

Test::Roundtrip_ptr
TAO::Objref_Traits<Test::Roundtrip>::nil ()
{
  return Test::Roundtrip::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Test::Roundtrip>::marshal (const Test::Roundtrip_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

::Test::Timestamp
Test::Roundtrip::test_method (
  ::Test::Timestamp send_time)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::CORBA::ULongLong>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::ULongLong>::in_arg_val _tao_send_time (send_time);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_send_time)
    };

  static TAO::Exception_Data
  _tao_Test_Roundtrip_test_method_exceptiondata [] = 
    {
      {
        "IDL:Test/InvalidTimestamp:1.0",
        Test::InvalidTimestamp::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , Test::_tc_InvalidTimestamp
#endif /* TAO_HAS_INTERCEPTORS */
      },

      {
        "IDL:Test/ServerOverload:1.0",
        Test::ServerOverload::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , Test::_tc_ServerOverload
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "test_method",
      11,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_Test_Roundtrip_test_method_exceptiondata,
      2
    );

  return _tao_retval.retn ();
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
Test::Roundtrip::shutdown ()
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      1,
      "shutdown",
      8,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_ONEWAY_INVOCATION,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _invocation_call.invoke (nullptr, 0);
}

Test::Roundtrip::Roundtrip ()
{
}
void
Test::Roundtrip::_tao_any_destructor (void *_tao_void_pointer)
{
  Roundtrip *_tao_tmp_pointer =
    static_cast<Roundtrip *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Test::Roundtrip_ptr
Test::Roundtrip::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TAO::Narrow_Utils<Roundtrip>::narrow (_tao_objref, "IDL:Test/Roundtrip:1.0");
}

Test::Roundtrip_ptr
Test::Roundtrip::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TAO::Narrow_Utils<Roundtrip>::unchecked_narrow (_tao_objref);
}

Test::Roundtrip_ptr
Test::Roundtrip::_nil ()
{
  return nullptr;
}

Test::Roundtrip_ptr
Test::Roundtrip::_duplicate (Roundtrip_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Test::Roundtrip::_tao_release (Roundtrip_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Test::Roundtrip::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:Test/Roundtrip:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Test::Roundtrip::_interface_repository_id () const
{
  return "IDL:Test/Roundtrip:1.0";
}

::CORBA::Boolean
Test::Roundtrip::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_typecode/objref_typecode.cpp:68

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Test_Roundtrip (
    ::CORBA::tk_objref,
    "IDL:Test/Roundtrip:1.0",
    "Roundtrip");
  

namespace Test
{
  ::CORBA::TypeCode_ptr const _tc_Roundtrip =
    &_tao_tc_Test_Roundtrip;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_typecode/value_typecode.cpp:63

static TAO::TypeCode::Value_Field<char const *, ::CORBA::TypeCode_ptr const *> const * const _tao_fields_Test_AMH_RoundtripExceptionHolder = 0;
static TAO::TypeCode::Value<char const *,
                     ::CORBA::TypeCode_ptr const *,
                     TAO::TypeCode::Value_Field<char const *, ::CORBA::TypeCode_ptr const *> const *,
                     TAO::Null_RefCount_Policy>
  _tao_tc_Test_AMH_RoundtripExceptionHolder (
    ::CORBA::tk_value,
    "IDL:Test/AMH_RoundtripExceptionHolder:1.0",
    "AMH_RoundtripExceptionHolder",
    ::CORBA::VM_NONE,
    &::CORBA::_tc_null,
    _tao_fields_Test_AMH_RoundtripExceptionHolder,
    0);
  

namespace Test
{
  ::CORBA::TypeCode_ptr const _tc_AMH_RoundtripExceptionHolder =
    &_tao_tc_Test_AMH_RoundtripExceptionHolder;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_cs.cpp:52



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


void
TAO::Value_Traits<Test::AMH_RoundtripExceptionHolder>::add_ref (Test::AMH_RoundtripExceptionHolder * p)
{
  ::CORBA::add_ref (p);
}

void
TAO::Value_Traits<Test::AMH_RoundtripExceptionHolder>::remove_ref (Test::AMH_RoundtripExceptionHolder * p)
{
  ::CORBA::remove_ref (p);
}

void
TAO::Value_Traits<Test::AMH_RoundtripExceptionHolder>::release (Test::AMH_RoundtripExceptionHolder * p)
{
  ::CORBA::remove_ref (p);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Test::AMH_RoundtripExceptionHolder *
Test::AMH_RoundtripExceptionHolder::_downcast (::CORBA::ValueBase *v)
{
  return dynamic_cast<::Test::AMH_RoundtripExceptionHolder *> (v);
}

const char *
Test::AMH_RoundtripExceptionHolder::_tao_obv_repository_id () const
{
  return this->_tao_obv_static_repository_id ();
}

void
Test::AMH_RoundtripExceptionHolder::_tao_obv_truncatable_repo_ids (Repository_Id_List& ids) const
{
  ids.push_back (this->_tao_obv_static_repository_id ());
}

void
Test::AMH_RoundtripExceptionHolder::_tao_any_destructor (void *_tao_void_pointer)
{
  AMH_RoundtripExceptionHolder *_tao_tmp_pointer =
    static_cast<AMH_RoundtripExceptionHolder *> (_tao_void_pointer);
  ::CORBA::remove_ref (_tao_tmp_pointer);
}

// TAO extension - the virtual _type method.
::CORBA::TypeCode_ptr Test::AMH_RoundtripExceptionHolder::_tao_type () const
{
  return ::Test::_tc_AMH_RoundtripExceptionHolder;
}

Test::AMH_RoundtripExceptionHolder::~AMH_RoundtripExceptionHolder ()
{}

::CORBA::ValueBase *
Test::AMH_RoundtripExceptionHolder::_copy_value ()
{
  ::CORBA::ValueBase *ret_val {};
  ACE_NEW_THROW_EX (
    ret_val,
    AMH_RoundtripExceptionHolder (),
    ::CORBA::NO_MEMORY ());
  return ret_val;
}

::CORBA::Boolean
Test::AMH_RoundtripExceptionHolder::_tao_marshal_v (TAO_OutputCDR &) const
{
  return true;
}

::CORBA::Boolean
Test::AMH_RoundtripExceptionHolder::_tao_unmarshal_v (TAO_InputCDR &)
{
  return true;
}

::CORBA::Boolean
Test::AMH_RoundtripExceptionHolder::_tao_match_formal_type (ptrdiff_t) const
{
  return false;
}

::CORBA::Boolean
Test::AMH_RoundtripExceptionHolder::_tao_marshal__Test_AMH_RoundtripExceptionHolder (TAO_OutputCDR &, TAO_ChunkInfo&) const
{
  return true;
}

::CORBA::Boolean
Test::AMH_RoundtripExceptionHolder::_tao_unmarshal__Test_AMH_RoundtripExceptionHolder (TAO_InputCDR &, TAO_ChunkInfo&)
{
  return true;
}

::CORBA::Boolean
Test::AMH_RoundtripExceptionHolder::_tao_unmarshal (
    TAO_InputCDR &strm,
    AMH_RoundtripExceptionHolder *&new_object)
{
  ::CORBA::ValueBase *base {};
  ::CORBA::Boolean is_indirected = false;
  ::CORBA::Boolean is_null_object = false;
  ::CORBA::Boolean const retval =
    ::CORBA::ValueBase::_tao_unmarshal_pre (
        strm,
        base,
        AMH_RoundtripExceptionHolder::_tao_obv_static_repository_id (),
        is_null_object,
        is_indirected
      );
  
  ::CORBA::ValueBase_var owner (base);

  if (!retval)
    return false;
  
  if (is_null_object)
    return true;
  
  if (!is_indirected && !base->_tao_unmarshal_v (strm))
    return false;
  
  // Now base must point to the unmarshaled object.
  // Align the pointer to the right subobject.
  new_object = AMH_RoundtripExceptionHolder::_downcast (base);
  if (nullptr == new_object)
    return false;
  
  if (is_indirected)
    new_object->_add_ref ();
  
  owner._retn ();
  return true;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_cs.cpp:442

void
Test::AMH_RoundtripExceptionHolder::raise_test_method ()
{
  std::unique_ptr< ::CORBA::Exception> safety (this->exception);
  this->exception->_raise ();
}

// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_cs.cpp:442

void
Test::AMH_RoundtripExceptionHolder::raise_shutdown ()
{
  std::unique_ptr< ::CORBA::Exception> safety (this->exception);
  this->exception->_raise ();
}

// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Test::AMH_RoundtripResponseHandler.

Test::AMH_RoundtripResponseHandler_ptr
TAO::Objref_Traits<Test::AMH_RoundtripResponseHandler>::duplicate (Test::AMH_RoundtripResponseHandler_ptr p)
{
  return Test::AMH_RoundtripResponseHandler::_duplicate (p);
}

void
TAO::Objref_Traits<Test::AMH_RoundtripResponseHandler>::release (Test::AMH_RoundtripResponseHandler_ptr p)
{
  ::CORBA::release (p);
}

Test::AMH_RoundtripResponseHandler_ptr
TAO::Objref_Traits<Test::AMH_RoundtripResponseHandler>::nil ()
{
  return Test::AMH_RoundtripResponseHandler::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Test::AMH_RoundtripResponseHandler>::marshal (const Test::AMH_RoundtripResponseHandler_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Test::AMH_RoundtripResponseHandler::AMH_RoundtripResponseHandler ()
{}void
Test::AMH_RoundtripResponseHandler::_tao_any_destructor (void *_tao_void_pointer)
{
  AMH_RoundtripResponseHandler *_tao_tmp_pointer =
    static_cast<AMH_RoundtripResponseHandler *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Test::AMH_RoundtripResponseHandler_ptr
Test::AMH_RoundtripResponseHandler::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return AMH_RoundtripResponseHandler::_duplicate (
      dynamic_cast<AMH_RoundtripResponseHandler_ptr> (_tao_objref));
}

Test::AMH_RoundtripResponseHandler_ptr
Test::AMH_RoundtripResponseHandler::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return AMH_RoundtripResponseHandler::_duplicate (
      dynamic_cast<AMH_RoundtripResponseHandler_ptr> (_tao_objref));
}

Test::AMH_RoundtripResponseHandler_ptr
Test::AMH_RoundtripResponseHandler::_nil ()
{
  return nullptr;
}

Test::AMH_RoundtripResponseHandler_ptr
Test::AMH_RoundtripResponseHandler::_duplicate (AMH_RoundtripResponseHandler_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Test::AMH_RoundtripResponseHandler::_tao_release (AMH_RoundtripResponseHandler_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Test::AMH_RoundtripResponseHandler::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:Test/AMH_RoundtripResponseHandler:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Test::AMH_RoundtripResponseHandler::_interface_repository_id () const
{
  return "IDL:Test/AMH_RoundtripResponseHandler:1.0";
}

::CORBA::Boolean
Test::AMH_RoundtripResponseHandler::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_typecode/objref_typecode.cpp:68

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Test_AMH_RoundtripResponseHandler (
    ::CORBA::tk_local_interface,
    "IDL:Test/AMH_RoundtripResponseHandler:1.0",
    "AMH_RoundtripResponseHandler");
  

namespace Test
{
  ::CORBA::TypeCode_ptr const _tc_AMH_RoundtripResponseHandler =
    &_tao_tc_Test_AMH_RoundtripResponseHandler;
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_obv_cs.cpp:43

OBV_Test::Red_Herring::~Red_Herring ()
{}

::CORBA::Boolean
OBV_Test::Red_Herring::_tao_marshal__Test_Red_Herring (TAO_OutputCDR &strm, TAO_ChunkInfo& ci) const
{
  return _tao_marshal_state (strm, ci);
}

::CORBA::Boolean
OBV_Test::Red_Herring::_tao_unmarshal__Test_Red_Herring (TAO_InputCDR &strm, TAO_ChunkInfo& ci)
{
  return _tao_unmarshal_state (strm, ci);
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_obv_cs.cpp:43

OBV_Test::AMH_RoundtripExceptionHolder::~AMH_RoundtripExceptionHolder ()
{}

::CORBA::Boolean
OBV_Test::AMH_RoundtripExceptionHolder::_tao_marshal__Test_AMH_RoundtripExceptionHolder (TAO_OutputCDR &strm, TAO_ChunkInfo& ci) const
{
  return _tao_marshal_state (strm, ci);
}

::CORBA::Boolean
OBV_Test::AMH_RoundtripExceptionHolder::_tao_unmarshal__Test_AMH_RoundtripExceptionHolder (TAO_InputCDR &strm, TAO_ChunkInfo& ci)
{
  return _tao_unmarshal_state (strm, ci);
}
// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_exception/any_op_cs.cpp:36


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Dual_Impl_T<Test::InvalidTimestamp>::demarshal_value (TAO_InputCDR & cdr)
  {
    ::CORBA::String_var id;

    if (!(cdr >> id.out ()))
      {
        return false;
      }
    
    try
      {
        this->value_->_tao_decode (cdr);
      }
    catch (const ::CORBA::Exception &)
      {
        return false;
      }

    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



/// Copying insertion.
void operator<<= (
  ::CORBA::Any &_tao_any,
  const Test::InvalidTimestamp &_tao_elem)
{
  TAO::Any_Dual_Impl_T<Test::InvalidTimestamp>::insert_copy (
    _tao_any,
    Test::InvalidTimestamp::_tao_any_destructor,
    Test::_tc_InvalidTimestamp,
    _tao_elem);
}

/// Non-copying insertion.
void operator<<= (
  ::CORBA::Any &_tao_any,
  Test::InvalidTimestamp *_tao_elem)
{
  TAO::Any_Dual_Impl_T<Test::InvalidTimestamp>::insert (
    _tao_any,
    Test::InvalidTimestamp::_tao_any_destructor,
    Test::_tc_InvalidTimestamp,
    _tao_elem);
}

/// Extraction to const pointer.
::CORBA::Boolean operator>>= (
  const ::CORBA::Any &_tao_any,
  const Test::InvalidTimestamp *&_tao_elem)
{
  return TAO::Any_Dual_Impl_T<Test::InvalidTimestamp>::extract (
    _tao_any,
    Test::InvalidTimestamp::_tao_any_destructor,
    Test::_tc_InvalidTimestamp,
    _tao_elem);
}
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_exception/any_op_cs.cpp:36


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Dual_Impl_T<Test::ServerOverload>::demarshal_value (TAO_InputCDR & cdr)
  {
    ::CORBA::String_var id;

    if (!(cdr >> id.out ()))
      {
        return false;
      }
    
    try
      {
        this->value_->_tao_decode (cdr);
      }
    catch (const ::CORBA::Exception &)
      {
        return false;
      }

    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



/// Copying insertion.
void operator<<= (
  ::CORBA::Any &_tao_any,
  const Test::ServerOverload &_tao_elem)
{
  TAO::Any_Dual_Impl_T<Test::ServerOverload>::insert_copy (
    _tao_any,
    Test::ServerOverload::_tao_any_destructor,
    Test::_tc_ServerOverload,
    _tao_elem);
}

/// Non-copying insertion.
void operator<<= (
  ::CORBA::Any &_tao_any,
  Test::ServerOverload *_tao_elem)
{
  TAO::Any_Dual_Impl_T<Test::ServerOverload>::insert (
    _tao_any,
    Test::ServerOverload::_tao_any_destructor,
    Test::_tc_ServerOverload,
    _tao_elem);
}

/// Extraction to const pointer.
::CORBA::Boolean operator>>= (
  const ::CORBA::Any &_tao_any,
  const Test::ServerOverload *&_tao_elem)
{
  return TAO::Any_Dual_Impl_T<Test::ServerOverload>::extract (
    _tao_any,
    Test::ServerOverload::_tao_any_destructor,
    Test::_tc_ServerOverload,
    _tao_elem);
}
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/any_op_cs.cpp:44


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Test::Red_Herring>::to_value (
      ::CORBA::ValueBase *&_tao_elem) const
  {
    ::CORBA::add_ref (this->value_);
    _tao_elem = this->value_;
    return true;
  }
}


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

/// Copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Test::Red_Herring *_tao_elem)
{
  #ifdef TAO_VALUETYPE_COPYING_ANY_INSERTION_USES_COPY_VALUE
    Test::Red_Herring *_tao_copy =
      _tao_elem ?
        Test::Red_Herring::_downcast (_tao_elem->_copy_value ())
        : nullptr;
    _tao_any <<= std::addressof(_tao_copy);
  #else
    ::CORBA::add_ref (_tao_elem);
    _tao_any <<= std::addressof(_tao_elem);
  #endif
}

/// Non-copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Test::Red_Herring **_tao_elem)
{
  TAO::Any_Impl_T<Test::Red_Herring>::insert (
    _tao_any,
    Test::Red_Herring::_tao_any_destructor,
    Test::_tc_Red_Herring,
    *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Test::Red_Herring *&_tao_elem)
{
  return
    TAO::Any_Impl_T<Test::Red_Herring>::extract (
        _tao_any,
        Test::Red_Herring::_tao_any_destructor,
        Test::_tc_Red_Herring,
        _tao_elem);
}


}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Test::Roundtrip>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



/// Copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Test::Roundtrip_ptr _tao_elem)
{
  Test::Roundtrip_ptr _tao_objptr =
    Test::Roundtrip::_duplicate (_tao_elem);
  _tao_any <<= std::addressof(_tao_objptr);
}

/// Non-copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Test::Roundtrip_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Test::Roundtrip>::insert (
    _tao_any,
    Test::Roundtrip::_tao_any_destructor,
    Test::_tc_Roundtrip,
    *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Test::Roundtrip_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Test::Roundtrip>::extract (
        _tao_any,
        Test::Roundtrip::_tao_any_destructor,
        Test::_tc_Roundtrip,
        _tao_elem);
}

}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/any_op_cs.cpp:44


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Test::AMH_RoundtripExceptionHolder>::to_value (
      ::CORBA::ValueBase *&_tao_elem) const
  {
    ::CORBA::add_ref (this->value_);
    _tao_elem = this->value_;
    return true;
  }
}


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

/// Copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Test::AMH_RoundtripExceptionHolder *_tao_elem)
{
  #ifdef TAO_VALUETYPE_COPYING_ANY_INSERTION_USES_COPY_VALUE
    Test::AMH_RoundtripExceptionHolder *_tao_copy =
      _tao_elem ?
        Test::AMH_RoundtripExceptionHolder::_downcast (_tao_elem->_copy_value ())
        : nullptr;
    _tao_any <<= std::addressof(_tao_copy);
  #else
    ::CORBA::add_ref (_tao_elem);
    _tao_any <<= std::addressof(_tao_elem);
  #endif
}

/// Non-copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Test::AMH_RoundtripExceptionHolder **_tao_elem)
{
  TAO::Any_Impl_T<Test::AMH_RoundtripExceptionHolder>::insert (
    _tao_any,
    Test::AMH_RoundtripExceptionHolder::_tao_any_destructor,
    Test::_tc_AMH_RoundtripExceptionHolder,
    *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Test::AMH_RoundtripExceptionHolder *&_tao_elem)
{
  return
    TAO::Any_Impl_T<Test::AMH_RoundtripExceptionHolder>::extract (
        _tao_any,
        Test::AMH_RoundtripExceptionHolder::_tao_any_destructor,
        Test::_tc_AMH_RoundtripExceptionHolder,
        _tao_elem);
}


}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Test::AMH_RoundtripResponseHandler>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}

namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Test::AMH_RoundtripResponseHandler>::marshal_value (TAO_OutputCDR &)
  {
    return false;
  }

  template<>
  ::CORBA::Boolean
  Any_Impl_T<Test::AMH_RoundtripResponseHandler>::demarshal_value (TAO_InputCDR &)
  {
    return false;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



/// Copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Test::AMH_RoundtripResponseHandler_ptr _tao_elem)
{
  Test::AMH_RoundtripResponseHandler_ptr _tao_objptr =
    Test::AMH_RoundtripResponseHandler::_duplicate (_tao_elem);
  _tao_any <<= std::addressof(_tao_objptr);
}

/// Non-copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  Test::AMH_RoundtripResponseHandler_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Test::AMH_RoundtripResponseHandler>::insert (
    _tao_any,
    Test::AMH_RoundtripResponseHandler::_tao_any_destructor,
    Test::_tc_AMH_RoundtripResponseHandler,
    *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Test::AMH_RoundtripResponseHandler_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Test::AMH_RoundtripResponseHandler>::extract (
        _tao_any,
        Test::AMH_RoundtripResponseHandler::_tao_any_destructor,
        Test::_tc_AMH_RoundtripResponseHandler,
        _tao_elem);
}

}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_exception/cdr_op_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Test::InvalidTimestamp &_tao_aggregate)
{
  // Marshal the repository ID.
  return (strm << _tao_aggregate._rep_id ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &,
    Test::InvalidTimestamp&)
{
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_exception/cdr_op_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Test::ServerOverload &_tao_aggregate)
{
  // Marshal the repository ID.
  return (strm << _tao_aggregate._rep_id ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &,
    Test::ServerOverload&)
{
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_valuetype.cpp:506



TAO_BEGIN_VERSIONED_NAMESPACE_DECL
void
CORBA::add_ref (Test::Red_Herring * vt)
{
  if (vt != 0)
    {
      vt->_add_ref ();
    }
}

void
CORBA::remove_ref (Test::Red_Herring * vt)
{
  if (vt != 0)
    {
      vt->_remove_ref ();
    }
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/cdr_op_cs.cpp:59


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean
operator<< (
    TAO_OutputCDR &strm,
    const Test::Red_Herring *_tao_valuetype)
{
  return
    ::CORBA::ValueBase::_tao_marshal (
        strm,
        _tao_valuetype,
        reinterpret_cast<ptrdiff_t> (&Test::Red_Herring::_downcast));
}

::CORBA::Boolean
operator>> (
    TAO_InputCDR &strm,
    Test::Red_Herring *&_tao_valuetype)
{
  return Test::Red_Herring::_tao_unmarshal (strm, _tao_valuetype);
}


TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/marshal_cs.cpp:189

::CORBA::Boolean
OBV_Test::Red_Herring::_tao_marshal_state (TAO_OutputCDR &, TAO_ChunkInfo &) const
{
  return true;
}

::CORBA::Boolean
OBV_Test::Red_Herring::_tao_unmarshal_state (TAO_InputCDR &, TAO_ChunkInfo &)
{
  return true;
}

void
OBV_Test::Red_Herring::truncation_hook ()
{
  this->require_truncation_ = true;
}


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_cs.cpp:50


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Test::Roundtrip_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Test::Roundtrip_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  // Narrow to the right type.
  _tao_objref = TAO::Narrow_Utils< ::Test::Roundtrip>::unchecked_narrow (obj.in ());

  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_valuetype.cpp:506



TAO_BEGIN_VERSIONED_NAMESPACE_DECL
void
CORBA::add_ref (Test::AMH_RoundtripExceptionHolder * vt)
{
  if (vt != 0)
    {
      vt->_add_ref ();
    }
}

void
CORBA::remove_ref (Test::AMH_RoundtripExceptionHolder * vt)
{
  if (vt != 0)
    {
      vt->_remove_ref ();
    }
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/cdr_op_cs.cpp:59


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean
operator<< (
    TAO_OutputCDR &strm,
    const Test::AMH_RoundtripExceptionHolder *_tao_valuetype)
{
  return
    ::CORBA::ValueBase::_tao_marshal (
        strm,
        _tao_valuetype,
        reinterpret_cast<ptrdiff_t> (&Test::AMH_RoundtripExceptionHolder::_downcast));
}

::CORBA::Boolean
operator>> (
    TAO_InputCDR &strm,
    Test::AMH_RoundtripExceptionHolder *&_tao_valuetype)
{
  return Test::AMH_RoundtripExceptionHolder::_tao_unmarshal (strm, _tao_valuetype);
}


TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/johnny/ACE/trunk/TAO/TAO_IDL/be/be_visitor_valuetype/marshal_cs.cpp:189

::CORBA::Boolean
OBV_Test::AMH_RoundtripExceptionHolder::_tao_marshal_state (TAO_OutputCDR &, TAO_ChunkInfo &) const
{
  return true;
}

::CORBA::Boolean
OBV_Test::AMH_RoundtripExceptionHolder::_tao_unmarshal_state (TAO_InputCDR &, TAO_ChunkInfo &)
{
  return true;
}

void
OBV_Test::AMH_RoundtripExceptionHolder::truncation_hook ()
{
  this->require_truncation_ = true;
}



